polls/urls.py
from polls.views import index, question,question_option, results,vote
from django.urls import path

app_name = 'polls'

urlpatterns = [
    path('', index, name = 'index'),
    path('questions/',question, name = 'question' ),
    path('question/<int:question_id>', question_option, name = 'question_option'),
    path('question/results/<int:question_id>',results, name = 'vote'),
    path('question/vote/<int:question_id>', vote, name = 'results')

]

pollster/urls.py
from django.contrib import admin
from django.urls import path, include
from polls.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.question

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.CharField(max_length=264)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice

polls/views.py
from django.shortcuts import render
from polls.models import Question, Choice
# Create your views here.
def index(request):
    return render(request, 'home.html')

def question(request):
     questions = list(Question.objects.all())
     return render(request, 'question.html', {'poll_questions':questions})

def question_option(request, question_id):
    question = Question.objects.get(id=question_id)
    options = list(question.choice_set.all())
    return render(request, 'options.html', {'options':options, 'question':question, 'question_id':question.id})

def results(request, question_id):
    question = Question.objects.get(id=question_id)
    option = question.choice_set.all()
    return render(request, 'results.html', {'options':option})

def vote(request, question_id):
    question = Question.objects.get(pk=question_id)
    option = question.choice_set.all()
    choice = question.choice_set.get(pk=request.POST["choice"])
    choice.votes += 1
    choice.save()
    return render(request, 'results.html', {'options':option, 'choice':choice})

polls/templates/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Polling site</title>
  </head>
  <body>
    <nav class='navbar navbar-light' style='background-color: #515c63'>
      <span class="navbar-brand ml-12 mx-auto pt-12 h2">Pollster</span>
    </nav>
    <br>
    <div class="container">
      <div class="card w-50" style="margin-left: 280px">
        <div class="card-body">
          <h5 class="card-title" style="margin-left: 180px">Welcome to Pollster</h5>
          <p class="card-text" style="margin-left: 120px">This is the polling app where you can cast your polls.</p>
          <a href="{% url 'polls:question' %}" class="btn btn-dark" style="margin-left: 200px">View Available Polls</a>
        </div>
      </div>
    </div>
  </body>
</html>

polls/templates/options.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <br>
    <a href="{% url 'polls:question' %}" class = "btn btn-dark" style="margin-left: 550px">Back to Polls</a>
    <h1 style = "margin-left: 380px;">{{question}}</h1>
    <br>
    <form method="POST" action="{% url 'polls:results' question.id %}"> {% csrf_token %}
    {% for option in options %}
      <div class="card" style="width: 500px; margin-left: 380px;">
        <div class="card-body">
          <p class = "card-text">
              <input type="radio" name="choice" id="button" value="{{option.id}}">
              <label for="button">{{option}}</label>
            <br>
          </p>
          <br>
        </div>
      </div>
      <br>
    {%endfor%}
      <input type="Submit" name="" value="Vote" class="btn btn-success" style="margin-left: 430px; width:400px;">
    </form>
  </body>
</html>

polls/templates/question.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Polling site</title>
  </head>
  <body>
    <nav class='navbar navbar-light' style='background-color: #515c63'>
      <span class="navbar-brand ml-12 mx-auto pt-12 h2">Pollster</span>
    </nav>
    <br>
    <h3 class = "heading" style="margin-left: 540px">Poll Questions</h3>
    {% for question in poll_questions %}
      <div class="card" style="width: 520px; margin-left: 390px">
        <div class="card-body">
          <p class="card-text">{{ question.question}}.</p>
            <a href="{% url 'polls:question_option' question.id %}" class="btn btn-primary">Vote</a>
              <!-- <a href="{% url 'polls:results' question.id %}" class="btn btn-dark">Results</a> -->
            </div>
          </div>
          <br>
          {%endfor%}
        </body>
    </html>

polls/templates/results.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Results</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <h1 style = "margin-left: 360px"><em>Thank you for voting to {{choice}}.Your vote has been counted</em></h1>
    <br>
    <div class="card" style="width: 30rem;margin-left: 400px;">
      <div class="card-header">
        Results
      </div>
    {% for option in options %}
      <ul class="list-group list-group-flush">
        <li class="list-group-item">{{option.choice}} Vote is {{option.votes}}</li>
    {% endfor %}
  </div>
  <br>
  <a href="{% url 'polls:question' %}" class="btn btn-success" style="margin-left: 420px">Back to question</a>
  <a href="{% url 'polls:index' %}" class = "btn btn-dark">Back to Home</a>
  </body>
</html>